name: parcial_1
description: 'Resolucion primer parcial'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  floor: ^1.5.0
  flutter:
    sdk: flutter
  go_router: ^14.1.2

dev_dependencies:
  build_runner: ^2.1.2
  floor_generator: ^1.4.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
